### ISSUE TITLE
Estas comparando dos variables diferentes.

### ISSUE THREAD

**Issue by juliancantillo** [pukoz89/JavaScriptClass#2]
https://github.com/pukoz89/JavaScriptClass/blob/47ca54bdb1fb56cffdf518a6e9b28c7088ff2095/tShirts.js#L15

Debería ser:
```js
(shirtSleeve >= 8.13) && (shirtSleeve < 8.38) 
```

Esto se repite en todas la comparaciones de Sleeve.

**Comment by pukoz89** [comment]
Mucho pendejo yo. Eso era.

**Comment by juliancantillo** [comment]
Cuando cierres un Issue puedes hacerlo con un commit. En el mensaje de commit pones closes#2 y lo cierra y deja un registro del commit que lo arregla.
